name: Handle Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Build GKI A12-5.10"]
    types:
      - completed
  
  # 手动触发
  workflow_dispatch:
    inputs:
      run_id:
        description: "输入构建成功的 Run ID (去Actions页面点开构建记录，URL最后的数字)"
        required: true
        type: string

jobs:
  upload-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Determine Run ID
        id: get_id
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TARGET_ID=${{ inputs.run_id }}" >> $GITHUB_ENV
            echo "Mode: Manual Trigger using Run ID ${{ inputs.run_id }}"
          else
            echo "TARGET_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
            echo "Mode: Auto Trigger from Workflow Run"
          fi

      - name: Download Metadata
        uses: actions/download-artifact@v4
        with:
          name: release_metadata
          path: release_info
          run-id: ${{ env.TARGET_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Kernel Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Kernel_Build_Output
          path: assets
          run-id: ${{ env.TARGET_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List Files (Debug)
        run: ls -R assets

      - name: Generate Build Date
        run: |
         BUILD_DATE=$(TZ=Asia/Shanghai date +'%m-%d')
         echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
         
      - name: Read Metadata
        run: |
         TAG_NAME_RAW=$(cat release_info/tag_name.txt)
         RELEASE_TITLE_RAW=$(cat release_info/release_title.txt)

         KERNEL_VERSION=$(echo "$TAG_NAME_RAW" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
         OS_PATCH_LEVEL=$(echo "$TAG_NAME_RAW" | sed -E 's/^v[0-9.]+-([0-9]{4}-[0-9]{2}).*/\1/')
         SUFFIX=$(echo "$TAG_NAME_RAW" | sed -E 's/.*_//')

         BUILD_DATE=$(TZ=Asia/Shanghai date +'%Y-%m-%d')

         TAG_NAME="v${KERNEL_VERSION}-${BUILD_DATE}（${OS_PATCH_LEVEL}_${SUFFIX}）"
         RELEASE_TITLE=$(echo "$RELEASE_TITLE_RAW" | sed -E "s/(${KERNEL_VERSION})/\1_${BUILD_DATE#2026-}/")

         echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
         echo "RELEASE_TITLE=$RELEASE_TITLE" >> $GITHUB_ENV
    
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_TITLE }}
          body_path: release_info/release_body.md
          files: |
            assets/**/*.zip
            assets/**/*.img
            assets/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
